# Generated by Django 4.0.4 on 2022-05-03 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_internal_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal_transfer_type',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Internal_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_value', models.IntegerField()),
                ('transfer_comission', models.IntegerField(default=0)),
                ('transfer_date', models.DateTimeField(default=datetime.datetime(2022, 5, 3, 23, 53, 8, 979209), null=True)),
                ('balance_dsc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_dsc', to='manager.balance')),
                ('balance_src', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_src', to='manager.balance')),
                ('transfer_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.internal_transfer_type')),
            ],
        ),
    ]
