# Generated by Django 4.0.4 on 2022-05-09 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_internal_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 59, 44, 214559), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 59, 44, 215558), null=True),
        ),
        migrations.CreateModel(
            name='Profile_specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.TextField()),
                ('specialist_lastname', models.TextField()),
                ('specialist_midlename', models.TextField(blank=True, default=None, null=True)),
                ('about', models.TextField()),
                ('path_photo', models.TextField()),
                ('url_video', models.TextField()),
                ('date_confirm_admin', models.DateTimeField(default=None, null=True)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 59, 44, 217560), null=True)),
                ('actual', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.customuser')),
            ],
        ),
    ]
