# Generated by Django 4.0.4 on 2022-05-10 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_service_alter_external_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 49, 49, 9795), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 49, 49, 10796), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 49, 49, 11796), null=True),
        ),
        migrations.CreateModel(
            name='Profile_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.profile_specialist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.service')),
            ],
        ),
    ]
