# Generated by Django 4.0.4 on 2022-05-10 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_external_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist_photo_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poto_type', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 1, 52, 560865), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 1, 52, 562866), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 1, 52, 563865), null=True),
        ),
        migrations.CreateModel(
            name='Specialist_documen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.TextField()),
                ('show_client', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.profile_specialist')),
            ],
        ),
    ]
