# Generated by Django 4.0.4 on 2022-05-10 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_specialist_photo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 3, 56, 895090), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 3, 56, 897093), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 3, 56, 898091), null=True),
        ),
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('create_date', models.DateTimeField()),
                ('remove_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('free', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist_presentation_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.TextField()),
                ('description', models.TextField()),
                ('photo_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.specialist_photo_type')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.profile_specialist')),
            ],
        ),
    ]
