# Generated by Django 4.0.4 on 2022-05-10 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_external_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 13, 14, 916423), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 13, 14, 918425), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 13, 14, 919425), null=True),
        ),
        migrations.CreateModel(
            name='User_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.TextField()),
                ('card_number', models.IntegerField()),
                ('card_period', models.TimeField()),
                ('account_number', models.IntegerField()),
                ('bank_name', models.TextField()),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.customuser')),
            ],
        ),
    ]
