# Generated by Django 4.0.4 on 2022-05-10 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_external_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason_for_refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_refund', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Refusal_or_refund_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 15, 20, 670826), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 15, 20, 671825), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 8, 15, 20, 673823), null=True),
        ),
    ]
