# Generated by Django 4.0.4 on 2022-05-10 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_external_transfer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 23, 12, 247874), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 23, 12, 249873), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 23, 12, 251873), null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_appointment_create', models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 23, 12, 258875))),
                ('time_appointment_delete', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_appointment_accept_specialist', models.DateTimeField(blank=True, default=None, null=True)),
                ('description_client', models.TextField(blank=True, default=None, null=True)),
                ('description_specialist', models.TextField(blank=True, default=None, null=True)),
                ('rejection', models.BooleanField(blank=True, default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_client', to='manager.customuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.profile_service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_specialist', to='manager.customuser')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.time_slot')),
            ],
        ),
    ]
