# Generated by Django 4.0.4 on 2022-05-10 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 31, 35, 482940)),
        ),
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 31, 35, 474938), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 31, 35, 476940), null=True),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 31, 35, 477939), null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_creation', models.DateField(default=datetime.datetime(2022, 5, 10, 10, 31, 35, 490941))),
                ('deletion_date', models.DateField(blank=True, default=None, null=True)),
                ('viewing_date', models.DateField(blank=True, default=None, null=True)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='message_user_from', to='manager.customuser')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='message_user_to', to='manager.customuser')),
                ('reply_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='manager.message')),
            ],
        ),
    ]
