# Generated by Django 4.0.4 on 2022-05-10 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 204638)),
        ),
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 194639), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 196637), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 209640)),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 197639), null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 210638)),
        ),
        migrations.AlterField(
            model_name='session_feedback',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 51, 39, 211638)),
        ),
        migrations.CreateModel(
            name='Removed_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_removal', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='removed_user', to='manager.customuser')),
                ('who_deleted', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='who_deleted', to='manager.customuser')),
            ],
        ),
    ]
