# Generated by Django 4.0.4 on 2022-05-10 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 857382)),
        ),
        migrations.AlterField(
            model_name='external_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 848382), null=True),
        ),
        migrations.AlterField(
            model_name='internal_transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 849382), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 863383)),
        ),
        migrations.AlterField(
            model_name='profile_specialist',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 851385), null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 865383)),
        ),
        migrations.AlterField(
            model_name='session_feedback',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 865383)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 56, 3, 867383))),
                ('date_sent_to_phone', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_sent_to_email', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_user', to='manager.customuser')),
            ],
        ),
    ]
