# Generated by Django 4.0.4 on 2022-06-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_customuser_verify_email_customuser_verify_phone_and_more'),
        ('manager', '0025_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
    ]
